try:
    import freecad
except ImportError:
    pass
import FreeCAD as App
import Part
from typing import Any

from .projector.plane import PlaneProjector
from .projector.cylinder import CylinderProjector
from .projector.line import LineProjector
from .projector.circle import CircleProjector
from .projector.ellipse import EllipseProjector

class CADProjector:
    """
    High-level projector class that aggregates 2D primitives generated by all 
    supported primitive projectors (Faces and Edges).
    """
    
    def __init__(self, shape: Part.Shape):
        self.shape = shape
        
    def project(self, view_direction: tuple[float, float, float]) -> list[dict[str, Any]]:
        results = []
        
        # 1. Project Faces (for edge-on / silhouette handling)
        for f_idx, face in enumerate(self.shape.Faces):
            if not hasattr(face, "Surface"):
                continue
            
            tid = face.Surface.TypeId
            projector = None
            
            if tid == "Part::GeomPlane":
                projector = PlaneProjector(face)
            elif tid == "Part::GeomCylinder":
                projector = CylinderProjector(face)
                
            if projector:
                face_results = projector.project(view_direction)
                # Inject direct topo_origins (Type 1 correspondence).
                # Origins are {dim, id, role} objects (AMVDG v0.3): dim 2 =
                # a Face degenerating to this 2D primitive (edge-on plane,
                # cylinder silhouette), role = the geometric relationship.
                for res in face_results:
                    res["topo_origins"] = [
                        {"dim": 2, "id": f"Face_{f_idx}", "role": res.get("role", "edge-on")}]
                results.extend(face_results)
                
        # 2. Project Edges (for standard 1D curve rendering)
        for e_idx, edge in enumerate(self.shape.Edges):
            if not hasattr(edge, "Curve"):
                continue
                
            tid = edge.Curve.TypeId
            projector = None
            
            if tid == "Part::GeomLine":
                projector = LineProjector(edge)
            elif tid == "Part::GeomCircle":
                projector = CircleProjector(edge)
            elif tid == "Part::GeomEllipse":
                projector = EllipseProjector(edge)
                
            if projector:
                edge_results = projector.project(view_direction)
                # Inject direct topo_origins (Type 1 correspondence)
                # Note: The edge ID matches the index logic used in GraphBuilder.
                for res in edge_results:
                    res["topo_origins"] = [
                        {"dim": 1, "id": f"Edge_{e_idx}", "role": res.get("role", "edge")}]
                results.extend(edge_results)
                
        return results

if __name__ == "__main__":
    print("=== CADProjector Unit Test ===")
    box = Part.makeBox(10, 20, 30)
    master = CADProjector(box)
    direction = (0, -1, 0)
    prims = master.project(direction)
    print(f"Generated {len(prims)} 2D primitives from Box.")
    for p in prims:
        print(p)
